### ISSUE TITLE
hey for fairness also add tangle functionality

### ISSUE THREAD

**Issue by TimDaub** [MichaelKreil/blockchain-plus#1]
Hi,

I saw that you have quite an opinionated approach towards blockchain. "[In my home country, everybody does as he pleases!](https://www.youtube.com/watch?v=t1-MvF0TTL0)". Hence, I think instead of using binary and blocks, you should allow choosing ternary logic and a tangle style structure too!

Lemme know what you think. Not sure if I'll be able to contribute to a PR though 😆 

👋🏼

**Comment by MichaelKreil** [comment]
Thank you very much for your contribution.
We have already enabled the interface for this and other features. Unfortunately, we haven't gotten around to documenting all features yet.
But you can add parameters like:

```js
blockchainPlus(1000, {tangle: true})

blockchainPlus(1000, {follow_laws_of_thermodynamics: "hell no"})

blockchainPlus(1000, {wrap_data_structure_in: ["🥓", "🧀"]})
```
